version: '3.1'
services:
  coursesAPI_DB:
    image: mysql:5.7
    container_name: coursesAPI_DB
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  coursesAPI:
    container_name: coursesAPI
    image: node:16
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=coursesAPI_DB
      - DB_NAME=coursesAPI_DB
      - DB_USER=root
      - DB_PASSWORD=password
      - SERVER_PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    # As duas opções a baixo correspondem ao -it
    tty: true # -t
    stdin_open: true # -i
    depends_on:
      - coursesAPI_DB
